// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUoU4ptpOcZplEXn6xj6nrvaPAHNDrVXo',
    appId: '1:1002299507727:web:2b9bf72e29546c727dcf7a',
    messagingSenderId: '1002299507727',
    projectId: 'colorist-c2717',
    authDomain: 'colorist-c2717.firebaseapp.com',
    storageBucket: 'colorist-c2717.firebasestorage.app',
    measurementId: 'G-2TZ2TK3304',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNK-NhrDpxcX8hJDF3nakhPWEpOV4ztUo',
    appId: '1:1002299507727:android:b44dd5815170731c7dcf7a',
    messagingSenderId: '1002299507727',
    projectId: 'colorist-c2717',
    storageBucket: 'colorist-c2717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAffWnLRwMt0gw2bA9xdnYTsEeLsRCnVY',
    appId: '1:1002299507727:ios:8a24c42ea84221df7dcf7a',
    messagingSenderId: '1002299507727',
    projectId: 'colorist-c2717',
    storageBucket: 'colorist-c2717.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAffWnLRwMt0gw2bA9xdnYTsEeLsRCnVY',
    appId: '1:1002299507727:ios:8a24c42ea84221df7dcf7a',
    messagingSenderId: '1002299507727',
    projectId: 'colorist-c2717',
    storageBucket: 'colorist-c2717.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUoU4ptpOcZplEXn6xj6nrvaPAHNDrVXo',
    appId: '1:1002299507727:web:cfe76b042420a7947dcf7a',
    messagingSenderId: '1002299507727',
    projectId: 'colorist-c2717',
    authDomain: 'colorist-c2717.firebaseapp.com',
    storageBucket: 'colorist-c2717.firebasestorage.app',
    measurementId: 'G-T80RR745D8',
  );
}
